setup: Use docker --format to fix local tags on recent docker versions
On recent docker versions (tested with docker 29), the output format of
`docker images` was changed, which causes:

	❯ . tcb-env-setup/tcb-env-setup.sh -a local
	WARNING: This output is designed for human readability. For machine-readable output, please use --format.
	Error: no local versions found!

This commit implements what the warning suggests, using `--format` to
get stable output and removing the need for a complex and non-portable
sed at the same time.

This fixes #5.